# -*- coding: utf-8 -*-
"""Copy of Untitled66.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oWB4KnLJ2vEHPb7CKbSexT-M1_QiMAO_
"""

def multiply_list(items):
    total = 1
    for x in items:
        total *= x
    return total
print(multiply_list([3,-2,5]))