# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled67.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QvNv49ikHWOKfgEMtWzg9r0Il_SfzMwh
"""

list1 = [1, 3, 5, 7, 9]
list2=[1, 2, 4, 6, 7, 8]
 
diff1= list(set(list1) - set(list2))
diff2=list(set(list2) - set(list1)) 
print(diff1)
print (diff2)