# -*- coding: utf-8 -*-
"""Copy of Untitled67.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YU4mcuiq6c5-9uBrizxHWhvopSiXhZ7K
"""

a=[] 
if not a:
   print ("List is empty")
else:
   print("List is not empty")







a=[10, 30,23,45] 
if not a:
   print ("List is empty")
else:
   print("List is not empty")