# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1McrK5w9zKzOWq0zDMu1LYIPFDG67ue8_
"""

from random import shuffle
name = ['Anil', 'charan', 'kiran', 'mahesh', 'Dileep', 'Kumar']
shuffle(name)
print(name)